### ISSUE TITLE
For a competition with more than 1 tasks, how is the final ranking calculated ?

### ISSUE THREAD

**Issue by ktgiahieu** [codalab/codabench#1010]
In a competition with multiple tasks, for example: [our competition](https://www.codabench.org/competitions/1084/?secret_key=7b1088c2-9b96-41b4-9bf3-3565ffcea796), how is the final ranking calculated? Can we change it to our preferences (average of the scores from 2 tracks, maximum ranking from 2 tracks, average ranking from 2 tracks?

<img width="1166" alt="image" src="https://github.com/codalab/codabench/assets/42331617/abb11964-4e25-4b73-bb9e-96e723b5baec">

Thank you.

**Comment by Didayolo** [comment]
I think right now that phases are independant. I guess the default ordering is done using the first task.

**Comment by ktgiahieu** [comment]
Hi Adrien,

Can you help us create a third column to fuse scores from 2 tasks, and the final ranking is based on that third column? Isabelle asked who can help with it and when can it be done.

**Comment by Didayolo** [comment]
I think this is a quite big development. A work-around is to have your scores in differents columns (instead of differents tasks). Then you can fuse the scores of the two columns in a thrid column.

See the Mini-AutoML bundle for an example of this:
https://github.com/codalab/competition-examples/tree/master/codabench/mini-automl

**Comment by Didayolo** [comment]
Related to #406
