### ISSUE TITLE
Stuck in "Preparing submission... this may take a few moments.."

### ISSUE THREAD

**Issue by ringdk** [codalab/codabench#1244]
Hello! 

I'm running the following ML competition today, and participants have flagged that their submissions are not being scored. It seems they're constantly stuck in "Preparing submission... this may take a few moments.."

Can anyone please advise on what's going wrong and how to fix it?

https://www.codabench.org/competitions/1734

Thanks!

Dan.

**Comment by acletournel** [comment]
We have encountered a network issue just before the week-end. The problem is solved now, submissions are processed correctly. Sorry for the inconvenience !

**Comment by Didayolo** [comment]
@ringdk The public instance is stable and provide compute workers in the default queue. It just happened that you tested it right after the network re-configuration and maintenance. The problem was solved quickly.

Of course you can also use your own server, but in many use cases that may take unnecessary efforts.

I don't think a paid version would prevent any possible problems to happen. However, you are welcome to contribute to the projet in any way, including financiary support.
