### ISSUE TITLE
Submission stuck on "preparing" status

### ISSUE THREAD

**Issue by stargazingdave** [codalab/codabench#1256]
If you are competition participant:
I'm trying to submit my results to the competition's site and it's stuck on "preparing" or "scoring".
I followed the instructions for the file's submission.
Another member of my team tried to submit the same file himself with his account name as the file's name and for him it worked.

- Competition: SP Cup 2024 Robovox.
- File format: zip file containing a text file with name: davidportal.txt, davidportal is the name displayed when I'm connected to my account.

- I'm using Firefox, also tried with Chrome
- The URL of the problem: https://www.codabench.org/competitions/1588/#/participate-tab

**Comment by ihsaan-ullah** [comment]
@stargazingdave  
 I have checked and your submission in status `Preparing` failed because of a docker pull failure. This is not related to the participants and can happen sometimes.

We are investigating the problem and will resolve it soon.

**Comment by stargazingdave** [comment]
I tried that. Now it's stuck on "scoring" status.

**Comment by juliojj** [comment]
Hi, I am having a similar problem in a challenge we are organising (https://www.codabench.org/competitions/1822). This is not the first time I face this problem, as it happened in another challenge few months ago. Some submissions get stuck with "scoring" status. I tried to cancel some of them (as organiser), and now some files are stuck at the "submitted" stage. Why this problem is so recurrent on Codabench? It does not happen with so high frequency on Codalab.

**Comment by ihsaan-ullah** [comment]
Closing this and tracking it in #1252
