### ISSUE TITLE
Download all the submission

### ISSUE THREAD

**Issue by Aktsvigun** [codalab/codabench#1305]
Dear team,

Would you please tell me how can I download all the submissions to my competition?

**Comment by ihsaan-ullah** [comment]
@Aktsvigun at the moment, you cannot download all submissions.

**Comment by johann-petrak** [comment]
This is something that seems like basic functionality really: why would you expect organizers to download submissions manually one by one?

Is there at least an API based approach or example code for how to download all submissions? 

I do not understand why this issue got closed rather than made into a rather important feature request.

**Comment by Didayolo** [comment]
@johann-petrak @Aktsvigun 

You are right that is it an important feature. This issue was closed because this is already reported here: #1232

**Comment by johann-petrak** [comment]
I was not sure about if this was the same because the description of #1232 mentions the leaderboard button but I can see that a comment there also mentions the submissions dialog. 
Referring to the submissions dialog for a project, I think it would be good to have all the actions which are available for single individual entries available with a bulk action button for all those entries which are checked (download, delete ...)
