### ISSUE TITLE
Confusion about directory stucture in docker image

### ISSUE THREAD

**Issue by ff98li** [codalab/codabench#1329]
Hi,

I'm working with the `codalab/codalab-legacy:py39` docker image to set up a task where participants submit their predictions, which will then be scored against ground truth data I've uploaded to reference data via ingestion program and scoring program:
![image](https://github.com/codalab/codabench/assets/55061801/ac6e907d-6046-4822-b09d-6fcd8c91da92)

But the reference data appears to be located in the `/app/output` directory, while the submitted files seem to be in `/app/ingested_program` (or the other way around since the files share the same names):  
![Screenshot 2024-02-13 at 9 32 14 PM](https://github.com/codalab/codabench/assets/55061801/8d4f1496-f439-4f0d-9ef0-690ce7d30758)
Additionally, the scoring program I uploaded doesn't seem to be present in the screenshot above where all files and directories are printed out.

Could someone provide clarity on the intended file path structure for reference data, submission files, and the scoring program within the docker image?

Thanks!

Edit:
Both in `/app/output` and `/app/ingested_program` are the submitted files. It will be very much appreciated if anyone familiar with codabench could explain where the uploaded reference data is located. Thanks again!

**Comment by ff98li** [comment]
Ok I figured it out

**Comment by Didayolo** [comment]
Hi @ff98li,

The reason why the submissions go to `/app/ingested_program` is because using an ingestion program is for **code submissions**. In your case, where you want simple **results submissions** (submission of predictions), you need only the scoring program, not the ingestion program.

Here is an example of competition bundle using only a scoring program:

https://github.com/codalab/competition-examples/tree/master/codabench/wheat_seeds/results_submission_bundle

Regarding the folders (`/app/input`, etc.), have a look at this part of the documentation:

https://github.com/codalab/codabench/wiki/Submission-Docker-Container-Layout#submission-container

I hope this helps.

**Comment by ff98li** [comment]
> Hi @ff98li,
> 
> The reason why the submissions go to `/app/ingested_program` is because using an ingestion program is for **code submissions**. In your case, where you want simple **results submissions** (submission of predictions), you need only the scoring program, not the ingestion program.
> 
> Here is an example of competition bundle using only a scoring program:
> 
> https://github.com/codalab/competition-examples/tree/master/codabench/wheat_seeds/results_submission_bundle
> 
> Regarding the folders (`/app/input`, etc.), have a look at this part of the documentation:
> 
> https://github.com/codalab/codabench/wiki/Submission-Docker-Container-Layout#submission-container
> 
> I hope this helps.

Thanks! This definitely helps. One last question: if no ingestion program is used, will the submitted files directly be placed in `/app/input/res`?

**Comment by Didayolo** [comment]
Yes, I think so. This is confirmed by the scoring program from the example I sent previously:

https://github.com/codalab/competition-examples/blob/master/codabench/wheat_seeds/results_submission_bundle/scoring_program/scoring.py
