### ISSUE TITLE
Leaderboard form: a submission rule per challenge phase

### ISSUE THREAD

**Issue by juliojj** [codalab/codabench#1331]
Hi Codabench developers,
In "Leaderboard form" we can select, among other options, "Force last" or "Force best".
It would be amazing if you could consider adding a functionality where we can select such option for each challenge phase, such that we could select, for example, to use "Force last" in a development phase, and "Force best" in a test (final) phase.
Thanks and best

**Comment by Didayolo** [comment]
Dear Julio,

Thank you for the suggestion. I think we are not going to work on implementing this right now, because we are focusing on bug fixes. If several organizers ask for this feature, we will consider it.

In the meantime, I added it into the following discussion: 

https://github.com/codalab/codabench/discussions/1334

Feel free to make other feature suggestions in the future. Best regards.
