### ISSUE TITLE
Execution Time Limit Capped at 600s

### ISSUE THREAD

**Issue by johanneskruse** [codalab/codabench#1422]
Hi,

The 'Execution Time Limit' is fixed at 600 seconds, and I cannot increase it. My competition has been running for a few weeks with the limit set to more than 600 seconds, but today my submissions started to fail.

These are two valid submissions, but from one hour to the next, they cannot exceed 600 seconds:
![Screenshot 2024-04-23 at 10 00 14](https://github.com/codalab/codabench/assets/43001334/a2c5cef4-0e36-4754-bfd4-b049bdfa1b23)

I am still able to decrease the 'Execution Time Limit': 
![Screenshot 2024-04-23 at 10 50 28](https://github.com/codalab/codabench/assets/43001334/1eea2471-47a0-49bf-bf8b-ff19034f4ef5)

Is there an explanation or a fix for this?

Link to [Ekstra Bladet News Recommendation Competition](https://www.codabench.org/competitions/2469/?secret_key=98314b2c-9237-471e-905c-2a88bf6a1d8a) 

Thank you very much!

**Comment by aporrasc** [comment]
Hello,
I am having the same problem.
Any possible solution? or is it a bug?
Thank you very much!

**Comment by ihsaan-ullah** [comment]
@Didayolo I think this is because of the latest changes 

Do you think 600 seconds is not enough?
MAX_EXECUTION_TIME_LIMIT=600

**Comment by Didayolo** [comment]
Hi @johanneskruse @aporrasc,

Indeed, we just merged the following change: #1154

It limits the execution time on the default queue (the queue of workers shared by default by all competitions), in order to avoid congestion with long jobs. 

The limit is currently set to 600 seconds, maybe it is a bit too extreme?

For now:
- I'll increase the limit to 1200 seconds
- If it is still too tight, consider [using your own compute workers](https://github.com/codalab/codabench/wiki/Compute-Worker-Management---Setup) (given that your are organizers)

Your feedback on this matter is appreciated in any case. What is the usual duration of the jobs in your competitions?

**Comment by aporrasc** [comment]
Any help on setting the compute worker?

I am able to run the compute_worker container using: _docker run -v /codabench:/codabench -v /var/run/docker.sock:/var/run/docker.sock -d --env-file .env --name compute_worker --restart unless-stopped --log-opt max-size=100m --log-opt max-file=3 codalab/competitions-v2-compute-worker:latest_  in Shell. 

A couple of questions raise:
1) Should there be something in a local folder called "codabench"?
2) I submit a test but never starts. I am using the same Broker URL.
![image](https://github.com/codalab/codabench/assets/145582914/587047d9-f824-46c5-9e0b-79426620f6f5)

Any easy-to-follow tutorial?

Thanks in advance!

**Comment by ihsaan-ullah** [comment]
@aporrasc 


1. Have you created a queue and used its broker URL in the compute worker `.env`
2. can you check the logs of your compute worker if it is running?
3. when you submit a submission, do you see any changes in the compute worker logs?

**Comment by aporrasc** [comment]
Finally, I got it.

But even now in my own computer as compute worker the time limit is set to 600 seconds.

Where can I modify this? Becuase I only know one way to do it, in the competition.yaml.

Thanks.

**Comment by ihsaan-ullah** [comment]
You can change the time limit in your phase settings 

<img width="368" alt="Screenshot 2024-04-26 at 2 31 34 PM" src="https://github.com/codalab/codabench/assets/13259262/87d9a11c-c645-453f-a32d-8ee7689300a3">

**Comment by Didayolo** [comment]
@johanneskruse Sorry for the inconvenience for your competition, and thank you for your understanding.

You absolutely CAN setup several workers in order to parallelize the computation. You can simply follow the exact same procedure on several computers (VMs or physical machines). Use the same `BROKER_URL`, so the different workers will be listening to the same custom queue.
