### ISSUE TITLE
Inconsistency between EasyMarkdownEditor's preview and actual effect

### ISSUE THREAD

**Issue by Junyi-99** [codalab/codabench#1500]
I am an organizer, here is the our competition link: https://www.codabench.org/competitions/edit/3283

In the "Pages" editor, EasyMarkdownEditor did not render the HTML with style, but in the final published page, it will.

I put a PoC here:
```html
<div style="width:200px; height: 200px; background: red">
</div>
```

This is a non-urgent issue that just causes confusions for the organizers.

**Comment by ihsaan-ullah** [comment]
In front of the page there is an eye icons, when you press that button, you can see how the page will look like without saving changes. Markdown editor is not showing the style because it is built to render only Markdown.

<img width="953" alt="Screenshot 2024-07-13 at 7 15 51 PM" src="https://github.com/user-attachments/assets/028ad449-2cb0-47d6-a82c-e361bbd9511b">

I am closing this because we have many bugs to fix and features to implement. If you want to contribute and fix this, we would appreciate your contribution. We may want to check the markdown thing in detail in the next big update of the UI.
