### ISSUE TITLE
Hide score in "My Submissions" tab

### ISSUE THREAD

**Issue by NetaMor** [codalab/codabench#1510]
Hi,
Is there an option to hide the scores in "My Submissions" tab?

Thanks.

**Comment by ihsaan-ullah** [comment]
No, there is no option

**Comment by Didayolo** [comment]
Hi @NetaMor,

Can you describe your use case for this feature?

For now I'll close this issue.

**Comment by salbatarni** [comment]
I do not want participants to view their test results, but I want to allow multiple submissions (different systems). Otherwise, they can optimize on test set.

**Comment by Didayolo** [comment]
Yes, this sounds interesting.

We can:
- Show the primary column score instead of the first score (if it's not only the case)
- **Add an option to hide the scores from "My Submissions" page**

The option should be independent from "hide leaderboard", "hide output", "hide column", etc. to give the maximum flexibility to organizers.

**Comment by raysonlaroca** [comment]
> I think we should either remove score from submissions tab or add an option for organizers to hide/unhide it. What do you think [@Didayolo](https://github.com/Didayolo)
> 
> * To check if the score shown is the primary column score

The feature of hiding the scores from "My Submissions" page would be **very interesting**.
