### ISSUE TITLE
Submission stuck in preparing status

### ISSUE THREAD

**Issue by jpbrunetsx** [codalab/codabench#1594]
Hi, 
We are experiencing issues on our two competitions : 
https://www.codabench.org/competitions/3282/
https://www.codabench.org/competitions/2378/

Until today both were running without issues, now submissions are stuck on "preparing" status. Both competitions run on the same private queue with workers on our servers. 

On the worker side all seems ok until getting the bundle, followed by the following error : 
Task compute_worker_run[ab80e469-45ca-4341-a24e-8d9aae058212] raised unexpected: URLError(ConnectionResetError(104, 'Connection reset by peer'))

**Comment by ObadaS** [comment]
Hello,

It seems like submissions on our default queue, as well as other private queues are not having this problem.
Could the problem be coming from your workers ?

Could you share more logs from your worker ? It seems like there is an initial connection that succeeds, since the submission updates from Submitting to Preparing, so it's not like the connection is reset from the start. Something must be going wrong after the initial connection.

2 things you could try:
1. Reboot the workers VM (and potentially the bare-bones machine they are on if possible, and if the VM reboot didn't fix the issue)
2. Create a new worker VM from scratch

**Comment by jpbrunetsx** [comment]
Thank you for the advices. We ended up restarting all worker with no luck. However once all submissions stuck in queue where submitted (and failed as described) it went back to normal. 
What we did observe was that submission started to get stuck once the current phase was finished, we extended it and did not observe this on the new submissions.
