### ISSUE TITLE
[V1 Bundle] No public data and starting kit in "Files" tab

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#277]
Hi,

In V1, after uploading the bundle, it automatically adds "Starting Kit" and "Public data" to the Files tab:

![participate1](https://user-images.githubusercontent.com/11784999/71149436-d6742f80-222e-11ea-8f68-4cf24579f1d4.png)

With the exact same bundle in V2, it doesn't:

![participate2](https://user-images.githubusercontent.com/11784999/71149442-d7a55c80-222e-11ea-9d77-6dc3721b7b14.png)

[Example bundle](https://drive.google.com/open?id=1fPiNkU-tn-2awkPGWsADY4yuV63QZLSU).

**Comment by jimmykodes** [comment]
Due to the switch from phases being based in datasets to being based in tasks, the notion of starting kit and public data have been somewhat replaced by solutions. But there is not a 1:1 correlation between these ideas, so "converting" a v1 bundle's starting kit and public data to a solution on v2 is not necessarily an acceptable solution (by my reckoning, at least). 

v2 does not currently have a notion of competition wide files beyond the solutions provided to any tasks present in the competition, though this could be a feature added down the road.

One possible solution in the mean time would be is to include these desire files in a GitHub repo or in google drive and supply a link to them in your "get_starting_kit.html" page. Though something handled in a more "automatic" way down the road is by far preferred.

**Comment by Didayolo** [comment]
OK thank you for your answer.

I let the issue open a bit to remember this suggestion.

**Comment by Didayolo** [comment]
Hey,

So, is there a way to add files in the "Files" tab automatically (just with the bundle upload)?

Thanks

**Comment by Didayolo** [comment]
> One possible solution in the mean time would be is to include these desire files in a GitHub repo or in google drive and supply a link to them in your "get_starting_kit.html" page.

Or maybe we can upload a file into Codalab and provide a public URL to it?

**Comment by Didayolo** [comment]
I confirm we can use Codalab's storage instead of Github or Google Drive.

The URL is then something like this:

`https://<INSTANCE-URL>/datasets/download/5eb37bf3-a74f-404c-8f45-623495cccbfa`

I see there is a `Files` in V2 competitions, but I can't find how to edit it.
