### ISSUE TITLE
Can't edit task

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#742]
It seems that we need to re-create a task from scratch when we just want to edit on of the program or dataset (e.g. updating the reference data). That is not convenient.

<img width="921" alt="Capture d’écran 2022-11-15 à 16 19 13" src="https://user-images.githubusercontent.com/11784999/201956686-dc0de956-e21d-4beb-99c9-da705eeac6a1.png">

# Todos:

- [x] Add taks edit functionality
- [x] show a message that rerunning the previous submissions may be needed and is responsibility of the organizer

**Comment by Didayolo** [comment]
Feature or bug?

**Comment by ihsaan-ullah** [comment]
What will happen to submissions which have used scoring program A and now it is changed to scoring program B. 

I think because the task creation is easy, it should stay as it is to avoid inconsistencies in competitions.


I am not sure if a task which is in use can be deleted.

**Comment by Didayolo** [comment]
Yes, I guess I was surprised at first but I think it is better to let it this way.

**Comment by BDonnot** [comment]
I am not sure this is the correct behaviour from the organizer side.

Indeed, it can be quite tedious to upload everything (reference data, ingestion program, scoring program, etc.) when we just want to change one of the above and not everything.

The organizer should be aware that if one the core of the task is changed then all submissions need to be recomputed and it's probably not the responsibility (in my opinion) of the codabench platform to limit this feature.

That's only an opinion from a "recurrent" organizer of competition: during the L2RPN competitions (the one i'm organizing on a yearly basis) it's quite common to modify slightly the scoring or ingestion program between two phases of the competition to adjust difficulty for example.

**Comment by Didayolo** [comment]
Thank you for your input Benjamin.

A side remark: the name of a task is used to chose the task in the editor, and is also displayed in the leaderboard. When we create several tasks (e.g. to change the scoring program), it is then hard to differentiate between the different task. Choosing a different name is not a satisfying solution because the name displayed in the leaderboard is then changed too.

**Comment by ihsaan-ullah** [comment]
@Didayolo 

This point from [BDonnot](https://github.com/BDonnot)

> Indeed, it can be quite tedious to upload everything (reference data, ingestion program, scoring program, etc.) when we just want to change one of the above and not everything.

I think he misunderstood the way a new task can be created. 

Let say we have `Task 1` with the following files used in `Phase 1` of a competition.


- `scoring program 1`
- `ingestion program 1`
- `input data 1`
- `reference data 1`

Now the organizer wants to change `input data` and `reference data` for `Phase 2`. So the orginzer has to just upload `input data 2` and `reference data 2` and create a new task `Task 2` with the followig:

- `scoring program 1`
- `ingestion program 1`
- `input data 2`
- `reference data 2`

Now the organizer can leave `Task 1` in `Phase 1` and use `Task 2` in `Phase 2`


I still believe that editing a task is not useful. In real-life scenarios, a task will not be changed during the phase but can be changed before a phase starts (maybe because of some changes in datasets or programs).



2nd point from Benjamin:

> The organizer should be aware that if one the core of the task is changed then all submissions need to be recomputed and it's probably not the responsibility (in my opinion) of the codabench platform to limit this feature.

This should be mentioned somewhere maybe in Edit Phase where participant changes the task

**Comment by ihsaan-ullah** [comment]
@Didayolo I added 2 todos in the main comment.

**Comment by Didayolo** [comment]
Let's keep track in the PR
