### ISSUE TITLE
We need more information in job status page

### ISSUE THREAD

**Issue by Didayolo** [codalab/codabench#744]
Here is the interface:

<img width="1153" alt="Capture d’écran 2022-11-16 à 14 17 05" src="https://user-images.githubusercontent.com/11784999/202191385-defb0b91-cc08-422e-9298-8687a7f31a38.png">

And the old one in CodaLab Competitions:

<img width="1158" alt="Capture d’écran 2022-11-16 à 14 18 20" src="https://user-images.githubusercontent.com/11784999/202191395-f897ed7a-066a-4894-8b7e-95d307aec7d9.png">

The queue (custom queue name or * for default) and the hostname (container ID) are especially important.

TODO:

- [x] **Hostname of both ingestion and scoring jobs**
Solved by: #1126 
- [x] Hostname
Solved by: #861
- [x] Make competition names as clickable links
Solved by: #897
- [x] **Queue name**
Solved by: #1091 
- [x] Have a way to differentiate and show/hide the "secondary submissions", which are hidden submissions made when there are multiple tasks
Solved by: #1096 
- [x] Add queue in submission
Solved by: #1114 

New feature - All users should be able to access the job status interface:
- [x] Admins should be able to see all queues (including the default queue)
- [x] users should be able to see status page with their own submissions only
Solved by: #1098 
- [x] Users should be able to see only the queue they are administrating. This is indeed useful when debugging and monitoring a competition
Solved by: #1098 
- [x] When this is done, we should add a button in the Queue Management page that redirects to the job status page.
Solved by: #1098 

Other TODOs (less important):
- [x] Make usernames as clickable links
Solved by #1092
- [x] Submission size
Solved by #1093
- _Run time (see also #610) (abandoned)_

**Comment by ihsaan-ullah** [comment]
@Didayolo what do you want to get here:

> Have a way to differentiate and show/hide the "secondary submissions", which are hidden submissions made when there are multiple tasks

From this screenshot
<img width="1130" alt="Screenshot 2023-08-20 at 1 32 54 PM" src="https://github.com/codalab/codabench/assets/13259262/5ef4ff20-3285-4dcf-be6f-f5088e61f290">
You can see that submission id 2 is the actual submission but id 3,4 are generated because this competition has 2 tasks. 
Do you want to show only submission id 2 and not 3,4?

**Comment by ihsaan-ullah** [comment]
@Didayolo 

Can you please explain these two points:

> Users should be able to see only the queue they are administrating
This is indeed useful when debugging and monitoring a competition

Where do you want to see queues? Right now we don't have queues in `server_status` page


> Have a way to differentiate and show/hide the "secondary submissions", which are hidden submissions made when there are multiple tasks

From this screenshot
<img width="1130" alt="Screenshot 2023-08-20 at 1 32 54 PM" src="https://github.com/codalab/codabench/assets/13259262/5ef4ff20-3285-4dcf-be6f-f5088e61f290">
You can see that submission id 2 is the actual submission but id 3,4 are generated because this competition has 2 tasks. 
Do you want to show only submission id 2 and not 3,4?

Note that submission id 2 is not the one running but 3 and 4

**Comment by Didayolo** [comment]
> Where do you want to see queues? Right now we don't have queues in server_status page

Currently, the whole page can be accessed only by admins. The goal here is to open this page to all users. What I meant was that an user should be able to see only the submissions made to his queues.

> Do you want to show only submission id 2 and not 3,4?

In the ideal case, we would see only submission 2, with a clear indication that it is a multi-task submission. For instance, you would have a clickable arrow, when you click on it the two other rows appear. The goal is to avoid to clutter the interface (think of a submission with 20 sub-tasks). Also to make it clear that it is actually the same submission.
