### ISSUE TITLE
multiple leaderboards

### ISSUE THREAD

**Issue by lbeziaud** [codalab/codabench#873]
Hi,

Having multiple leaderboards seems currently impossible. Manual addition once there is a leaderboard is disabled. `competition.yaml` allows for multiple leaderboards to be defined (key `leaderboards` is plural and type is a list) however only the first one is created when the bundle is submitted.

**Comment by Didayolo** [comment]
Hi,

Indeed the `competition.yaml` implies that you can have several leaderboards, but currently it is not the case in the backend. Defining multiple leaderboards simply does nothing right now (maybe the code does store other leaderboards but do nothing about them).

The question is: do we need to be able to define multiple leaderboards? What would be use cases of this?

We already have "tasks" and "phases". Having multiple tasks act as having multiple leaderboards. Adding a new granularity could make the code more complex, so we should do it only if it is really useful.

**Comment by Didayolo** [comment]
I agree. Maybe we could add some UI options to improve the display, and avoid having a too long horizontal table.

Some options:

- Being able to divide into several tables (several "leaderboards") e.g. an option to display tasks vertically instead of horizontally.

- Buttons to hide/show each task. That would help to navigate through the long horizontal table.

**Comment by ihsaan-ullah** [comment]
shifted to discussion #1334
